version: '3'

services:
  rippled:
    ports:
      - 5005:5005
      - 5006:5006
    image: ulamlabs/ripple-testnet:latest
    build:
      context: ./ripple-testnet
    volumes:
      - ./rippled-data:/var/lib/rippled/db
  ripple-dashboard:
    container_name: ripple-dashboard
    build:
      context: ./ripple-dashboard
    ports:
      - 10080:10080
    environment:
      - RIPPLE_NODE_IP=ws://localhost:5006
